image:
  file: .gitpod.Dockerfile

ports:
  - port: 5678
    onOpen: open-browser

tasks:
  - name: Setup n8n
    init: |
      # Install Node.js 20
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      nvm install 20
      nvm use 20
      
      # Install n8n
      npm install -g n8n --prefix=/workspace/.npm-global
      echo 'export PATH="/workspace/.npm-global/bin:$PATH"' >> ~/.bashrc
      
      # Create persistent folders
      mkdir -p /workspace/n8n_data/{config,.n8n}
      ln -s /workspace/n8n_data/.n8n ~/.n8n
      
      # Make script executable
      chmod +x start-n8n.sh
    command: ./start-n8n.sh